server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456zcl
    # 关键修改：在 url 末尾加上 &allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.hwadee.cdutproject.entity

maid:
  # 📸 照片在服务器本地存储的绝对路径（主人可以根据自己的电脑系统修改，比如 D:/maid/uploads/）
  upload-folder: D:/maid/uploads/


logging:
    level:
      org.mybatis: DEBUG
      org.mybatis.spring: DEBUG
      com.hwadee.cdutproject: DEBUG

